apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      name: flaskapp-pod
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp-container-pod
        image: sima2610/flask-app
        port:
        - containerPort: 5000