apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: redis-replicaset
  labels:
    app: redisbook
    tier: redis
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:3.2-alpine
        ports:
        - containerPort: 6379